### ISSUE TITLE
Request for Code to Generate Connectivity Data Files

### ISSUE THREAD

**Issue by kfuruya127** [philshiu/Drosophila_brain_model#6]
Hello,

I am currently working on applying the model to the FlyWire Dataset v783. However, I am unsure of the proper method to create the complete list of Flywire neurons as a CSV file, as well as the connectivity data in a Parquet format from the FlyWire Dataset.

Could you please share the code to generate these files? Your help would be greatly appreciated.

Thank you in advance for your assistance.

**Comment by philshiu** [comment]
Let me check with flywire to see if there's a simple way to download this data, otherwise I'll send you code to do this.

**Comment by philshiu** [comment]
I've added the v783 configured files.

**Comment by kfuruya127** [comment]
Thank you so much for sharing the files.
I’ve successfully tested them, and everything seems to be working perfectly. I truly appreciate your help with this issue.

I will go ahead and close this issue now. Thanks again for your support.
