### ISSUE TITLE
Running the figures.ipynb notebook on data version 783 results in error KeyError: 720575940620900446

### ISSUE THREAD

**Issue by alphalzh** [philshiu/Drosophila_brain_model#7]
Hi, thanks for open sourcing the code.
I finished running the code with the old data ( data version 630) and it all went well.
When I was trying to run the figures.ipynb on the new data (public data 783) by changing the config to:
config = {
    'path_comp' : './Completeness_783.csv',        # completness data
    'path_con'  : './Connectivity_783.parquet',    # connectivity data
    'n_proc'    : 105,                                               # number of CPU cores (-1: use all)
}
I get the following error when running the first simulation in figure 1D:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[4], line 7
      3 for f in freqs:
      5     params['r_poi'] = f * Hz
----> 7     run_exp(exp_name='sugarR_{}Hz'.format(f), neu_exc=neu_sugar, params=params, **config)

File ~/git_repos/Drosophila_brain_model/model.py:357, in run_exp(exp_name, neu_exc, path_res, path_comp, path_con, params, neu_slnc, neu_exc2, n_proc, force_overwrite)
    355 start = time() 
    356 with parallel_backend('loky', n_jobs=n_proc):
--> 357     exc = [ flyid2i[n] for n in neu_exc ]
    358     exc2 = [ flyid2i[n] for n in neu_exc2 ]
    359     slnc = [ flyid2i[n] for n in neu_slnc ]

File ~/git_repos/Drosophila_brain_model/model.py:357, in <listcomp>(.0)
    355 start = time() 
    356 with parallel_backend('loky', n_jobs=n_proc):
--> 357     exc = [ flyid2i[n] for n in neu_exc ]
    358     exc2 = [ flyid2i[n] for n in neu_exc2 ]
    359     slnc = [ flyid2i[n] for n in neu_slnc ]

KeyError: 720575940620900446

It seems that some neurons used in the code are no longer present in the data version 783. Is this supposed to be the case? Why are these neurons not present? What should I do to change the code to fit the new data? Thanks in advance.

**Comment by philshiu** [comment]
Hi Ziheng Liao,

When someone edits a neuron in Flywire, the entire Flywire ID changes. For
example, 720575940620900446 in 630 became 720575940639259967 in 783.

I'm not sure if there's a fast way to figure out the new IDs, but if you go
to codex.flywire.ai, then change your version to 630 (top right), you
should be able to search for your neuron ID. In general, this should give
you a name for that ID, e.g., "GNG.1495". Then, search for that name in
783, and you should get the corresponding neuron in 783.

I hope this is helpful!
